const router = require("express").Router();

const user = require("./user");
const userType = require("./userType");
const category = require("./category");
const subcategory = require("./subcategory");
const post = require("./post");
const contact = require("./contact");
const comment = require("./comment");
const family = require("./family");
const genus = require("./genus");
const genusFeature = require("./genusFeature");
const province = require("./province");
const status = require("./status");
const problem = require("./problem");
const epidemic = require("./epidemic");
const epidemicHistory = require("./epidemicHistory");
const land = require("./land");
const household = require("./household");
const plant = require("./plant");
const plantHistory = require("./plantHistory");
const manure = require("./manure");
const characteristic = require("./characteristic");
const plantingTechnique = require("./plantingTechnique");
const handleFlower = require("./handleFlower");

router.use("/users", user);
router.use("/userTypes", userType);
router.use("/categories", category);
router.use("/subcategories", subcategory);
router.use("/posts", post);
router.use("/contacts", contact);
router.use("/comments", comment);
router.use("/families", family);
router.use("/genera", genus);
router.use("/genusFeatures", genusFeature);
router.use("/provinces", province);
router.use("/statuses", status);
router.use("/problems", problem);
router.use("/epidemics", epidemic);
router.use("/epidemicHistories", epidemicHistory);
router.use("/lands", land);
router.use("/households", household);
router.use("/plants", plant);
router.use("/plantHistories", plantHistory);
router.use("/manures", manure);
router.use("/characteristics", characteristic);
router.use("/plantingTechniques", plantingTechnique);
router.use("/handleFlowers", handleFlower);

module.exports = router;
